version: '3.9'

services:
  db:
    container_name: SecurityContainer
    image: postgres:15.1
    environment:
      POSTGRES_USER: Vlad
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TestSecDB
    ports:
      - "5432:5432"

  pgadmin:
    container_name: MyDBContainer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vladikzavgorodny@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"