spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/TestLiquibaseDB
        username: test_user
        password: test_password
        driver-class-name: org.postgresql.Driver
    liquibase:
        change-log: classpath:db/changelog-master.yaml

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true