spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LiquibaseDB
    username: Vlad
    password: root
    own:
      username: ${CONTAINER.USERNAME}
      password: ${CONTAINER.PASSWORD}
      url: ${CONTAINER.URL}

  liquibase:
    contexts: ${CONTAINER.LIQUIBASE}